# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        none

# Setup
title:            Playbook
tagline:          'A one stop guide to running projects at Invo.'
description:      'A one stop guide to running projects at Invo.'
url:              http://playbook.goinvo.com
baseurl:          /

author:
  name:           'Involution Studios'
  url:            https://twitter.com/goinvo

paginate:         5

# Custom vars
version:          0.4

github:
  repo:           https://github.com/goinvo/InvoPlaybook
