markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Eric Benoit
url: http://playbook.goinvo.com
description: Your guide to being an Invo'ite.
twitter: ebenoit
